// Code generated by MockGen. DO NOT EDIT.
// Source: MarvelRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	marvel "github.com/hayk99/marvelapp/pkg/domain/marvel"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SaveComic mocks base method.
func (m *MockRepository) SaveComic(marvelComic marvel.MarvelComic) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveComic", marvelComic)
}

// SaveComic indicates an expected call of SaveComic.
func (mr *MockRepositoryMockRecorder) SaveComic(marvelComic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveComic", reflect.TypeOf((*MockRepository)(nil).SaveComic), marvelComic)
}
