// Code generated by MockGen. DO NOT EDIT.
// Source: ComicRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	comic "github.com/hayk99/marvelapp/pkg/domain/comic"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ListAllComics mocks base method.
func (m *MockRepository) ListAllComics() ([]comic.Comic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllComics")
	ret0, _ := ret[0].([]comic.Comic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllComics indicates an expected call of ListAllComics.
func (mr *MockRepositoryMockRecorder) ListAllComics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllComics", reflect.TypeOf((*MockRepository)(nil).ListAllComics))
}

// SaveComic mocks base method.
func (m *MockRepository) SaveComic(comic comic.Comic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveComic", comic)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveComic indicates an expected call of SaveComic.
func (mr *MockRepositoryMockRecorder) SaveComic(comic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveComic", reflect.TypeOf((*MockRepository)(nil).SaveComic), comic)
}
